### PR TITLE
Add docker build

### PR DESCRIPTION
**Pull request by mkuf**
Hi,

I'd like to run moonraker-obico in Docker to be able to add it to my project: https://github.com/mkuf/prind

This PR adds:

* A Dockerfile at the Root of the repository
* A github workflow that builds the docker image and uploads it to ghcr.io
* A few lines of documentation about the image in the main Readme

Commits to the master Branch will build the `latest` tag for the Image.
Tagged commits will result in an image tag equal to the git tag.

For the Workflow to function, you'll have to enable Read and Write Permissions at `Settings/Actions/General/Workflow Permissions`, otherwise the Image upload to ghcr will fail.

Looking forward to your response.
-Markus

### CODE REVIEW

**Comment by kennethjiang** [comment]
Thank you so much @mkuf for the PR. I have been really busy this week. But will take a look probably this weekend.

**Comment by kennethjiang** [comment]
Good job! I think this is a solid PR. Only 1 think: I'd like to have the content README.md for the users who run moonraker-obico on a SBC, which is majority of the case. Can you move the new documentation to `run_as_container.md`, and have a reference README.md for the people who have similar needs as yours?

**Comment by mkuf** [comment]
Thanks for your feedback, I'm happy you like it.  
I just pushed an update which moves the container related documentation to an extra file, as requested.

**Comment by kennethjiang** [comment]
Merged. Thanks again @mkuf for the PR!

**Comment by mkuf** [comment]
Great :) 
I just checked the github action and the build/push was successful, the image is not visible though. 
Can you check in visibility settings for the package?

**Comment by kennethjiang** [comment]
It looks like I didn't do it right. I'm not familiar with github packages and access token. If you have a link to a tutorial that will be great. Otherwise, I can just search it in google or ask chatgpt. :D

**Comment by mkuf** [comment]
The workflow permissions I mentioned in my first comment should be set correctly, otherwise the github action would have failed. 

Just for reference, it should look like this, wenn you open this link https://github.com/TheSpaghettiDetective/moonraker-obico/settings/actions
image
<br>
My guess is, that the permission for the package is set incorrectly.  
For my fork, if I click on the package, I can access the `Package Settings` at the bottom of the the right column.  
image
<br>
Scrolling all the way to the bottom there, I can change the visibility settings for that package: 
image

I'm not sure if this is any different if packages are associated to a organization instead of a user, so take this with a grain of salt 😅

**Comment by kennethjiang** [comment]
It looks like an org repo just has a different way to get to the same pages. And everything looks right.

Screenshot 2023-08-20 at 7 43 11 AM
Screenshot 2023-08-20 at 7 43 24 AM

**Comment by kennethjiang** [comment]
Maybe you can find me (go by @kennethooo) on in our discord https://obico.io/discord/ so that we can debugging it together more easily?

**Comment by mkuf** [comment]
At the bottom of your first screenshot, the package is set to private.  
If you change that to public, it is available for all. 
image

**Comment by kennethjiang** [comment]
Ah! Don't understand why I missed that! After a couple more twists and turns I think I have made it as public. Can you try it again?

**Comment by mkuf** [comment]
Great 😃 

It's now visible alongside the Repo and I was able to pull it onto my machine.  

```
markus@havok:~$ docker pull ghcr.io/thespaghettidetective/moonraker-obico:latest
latest: Pulling from thespaghettidetective/moonraker-obico
52d2b7f179e3: Pull complete 
2b8a9a2240c1: Pull complete
051d6521462a: Pull complete
fce84b1f897c: Pull complete
46233543d8c2: Pull complete
ce7b91523a81: Pull complete
4f4fb700ef54: Pull complete
4a57fb54a66b: Pull complete
0ee1a359a912: Pull complete
e9ea676ab5a2: Pull complete
5303a9630468: Pull complete
Digest: sha256:b16a4e02712a0ac8979fece8f23bae26c087e604a25b3a9d631cf9a56e10d7fb
Status: Downloaded newer image for ghcr.io/thespaghettidetective/moonraker-obico:latest
ghcr.io/thespaghettidetective/moonraker-obico:latest
```

Thanks a lot.

-Markus

**Comment by mkuf** [comment]
Just an FYI, moonraker-obico has been added to prind: https://github.com/mkuf/prind/releases/tag/v1.9.0

**Comment by kennethjiang** [comment]
Love your project. Cute logo with  the whale carrying the printers. :D

**Pull request merged**
